version: '3.1'

# Run proxy server and Total.js Code
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx:/etc/nginx/conf.d

  code:
    container_name: code
    image: totalplatform/code
    volumes:
      - codedata:/code/databases
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /your/local/path/apps/:/www/www              # Edit development folder
    environment:
      - FOLDER_WWW=/your/local/path/apps             # Edit development folder
      - FOLDER_NPM=/your/local/path/node_modules     # Edit node_modules folder
      - VIRTUAL_MAX_UPLOAD=100
      - VIRTUAL_HOST=code.localhost
      - VIRTUAL_PORT=8000
      - DISABLE_ACCESS_LOGS=1

volumes:
  codedata:

networks:
  default:
    name: proxy